version: '3.7'
services:
  nginx-server:
    container_name: nginx-server
    image: nginx:1.17
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - php

  php:
    image: php:8.0.3-fpm-buster
    container_name: php
    restart: always
    volumes:
      - ./html/:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini